my:
    greeting: Hello World from config server updated 
    list: one,two,three, congfigServer updated new update 
app: 
    name: My app congfigServer updated new update
    descrption: welcome to ${app.name}
db:
    connection: "{connection:'https://congfigServer updated',user:'footest', pass:'pass' }"
    port: 3309
    host: 127.168.1.1
