my:
    greeting: Hello World from config server updated New changes
    list: one,two,three, congfigServer updated New changes
app: 
    name: My app congfigServer updated New changes
    descrption: welcome to ${app.name}
db:
    connection: "{connection:'https://congfigServer updated',user:'footest', pass:'pass' }"
    port: 3309
    host: 127.168.1.1
