my:
    greeting: Hello World from config server 
    list: one,two,three, congfigServer 
app: 
    name: My app congfigServer
    descrption: welcome to ${app.name}
db:
    connection: "{connection:'https://congfigServer updated',user:'foo', pass:'pass' }"
    port: 3309
    host: 127.168.1.1
